---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: headscale-operator
    app.kubernetes.io/part-of: headscale
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale-operator
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headscale-operator
        app.kubernetes.io/part-of: headscale
    spec:
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
        - name: headscale-operator
          image: {{ if .Values.steiger}}{{ .Values.steiger.headscaleOperator.image }}{{ else }}{{ .Values.deployment.image }}{{end}}
          args: ["/bin/headscale-operator", "run"]
          env:
            - name: RUST_LOG
              value: "info,headscale_operator={{ .Values.deployment.logLevel }}"
            - name: TLS_CERT_PATH
              value: /run/secrets/tls
            - name: CONFIG_MANAGER_IMAGE
              value: {{ if .Values.steiger}}{{ .Values.steiger.configManager.image }}{{ else }}{{ .Values.configManager.image }}{{end}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: webhook
              protocol: TCP
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 40m
              memory: 80Mi
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-tls
