---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app.kubernetes.io/name: headscale-operator
    app.kubernetes.io/part-of: headscale
spec:
  selector:
    app.kubernetes.io/name: headscale-operator
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
