apiVersion: headscale.juliamertz.dev/v1alpha1
kind: Policy
metadata:
  name: example
spec:
  headscaleRef:
    name: example
  acls:
    - action: accept
      src: ['kubernetes@']
      dst: ['homelab@:80,433']
    - action: accept
      src: ['julia@']
      dst: ['*:*']
