apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - namespace.yaml
  - certificate.yaml
  - database.yaml
  - headscale.yaml
  - user.yaml
  - acls.yaml
  - preauth-key.yaml
