apiVersion: headscale.juliamertz.dev/v1alpha1
kind: PreauthKey
metadata:
  name: example
spec:
  ephemeral: true
  reusable: true
  expiration: 99999h
  targetSecret: tailscale-agent-auth
  user:
    name: kubernetes 

