crds:
  install: false

deployment: 
  replicas: 1
  logLevel: debug
  terminationGracePeriodSeconds: 15
  image: 
    repository: ghcr.io/juliamertz/headscale-operator/headscale-operator
    tag: v0.0.4

configManager:
  image:
    repository: ghcr.io/juliamertz/headscale-operator/config-manager
    tag: v0.0.4
